import { operator, NOTICE_VERSION } from "@/lib/platform/privacy";
export function PrivacyNotice() {
 const o=operator();
 return <>
 <h2>Parent notice · Questburrow</h2><p>Notice version {NOTICE_VERSION}. For parents and guardians of children under 13.</p>
 <h3>Who operates this service</h3><p>{o.name || "Operator name pending — public registration is closed"}<br/>{o.address || "Mailing address pending"}<br/>{o.email || "Contact email pending"}<br/>{o.phone || "Contact telephone pending"}</p>
 <h3>What we collect and why</h3><p>Your parent email and account identifier support sign-in and account administration. With your permission, we store child nicknames, preset avatars, grades, assignments, protected PINs, question responses, learning records, rewards and saved game progress. We use these to provide your family’s games, adjust assigned learning and save progress. Please use nicknames and do not enter children’s full names, contact details, health information or other sensitive information into names, answers, notes or question banks.</p>
 <p>Connection information such as IP addresses, necessary cookies and security logs may be processed to deliver and protect the service. We do not offer advertising, public child profiles, chat, child photos, voice recording, or customer AI question generation. We do not sell children’s information or use it to train AI models. Custom question banks are private during the initial public launch.</p>
 <h3>Providers and access</h3><p>The planned production providers are Render (hosting, stored records and connection logs), Clerk (parent authentication, account identifiers, email and sign-in security), and Stripe (parent billing if you subscribe). Stripe processes payment details; Questburrow does not store full card numbers. These providers receive information needed for their functions. The operator and authorized support personnel can access records to operate the service and respond to parent requests. Agent API keys allow limited official-catalog tasks and aggregate reports; they do not permit access to child profiles, consent forms or account deletion.</p>
 <h3>Your choice before children play</h3><p>We request your permission to collect and use the child information described here and to process it through the service providers needed to run Questburrow. Print this notice and consent form, sign and date it, and upload a scan or photo of only the completed form in Parent permission. The operator reviews it before enabling child profiles and games. No payment is required for consent. A parent account or an ordinary login alone does not activate permission.</p>
 <h3>Review, withdraw and delete</h3><p>In parent space you can review profiles and learning records, export family data, delete individual children, or withdraw permission. Withdrawal immediately disables child access and removes all child profiles, game saves, learning records, rewards and private question banks from the active database. Withdrawal alone does not cancel a subscription. Delete family account cancels any connected subscription and opens a provider-account deletion request for the operator. You may also contact us above; we verify that requests come from the parent before releasing records. We do not require information beyond what is reasonably necessary for an activity.</p>
 <h3>Retention</h3><p>Pending forms expire after 7 days. Form images are encrypted in the active database and removed upon review or expiry; minimal version, decision and verification evidence is kept while permission is active and for up to 1 year after withdrawal or expiry. Child data and private banks are removed after 12 months without parent or child activity. Detailed native lesson receipts are retained up to 1 year; necessary game progress and cumulative rewards remain while the account is active. Security audit records expire after 90 days; challenges after 24 hours; completed account-deletion request records after 30 days.</p>
 <p>Pending provider-account deletion requests remain until resolved and must be reviewed by the operator weekly. Provider-held parent authentication and billing records follow their own applicable retention requirements; records legally required for taxes or payment disputes may be retained. Backups are restricted to recovery, expire within 30 days under the launch backup procedure, and deletions must be reapplied before a restored copy serves users. These operating procedures must be configured before public registration opens.</p>
 <p>If permission is not obtained, the operator deletes consent-request contact records and closes unused parent accounts within 30 days. Material changes require an updated notice and renewed permission. See the privacy page at /privacy for the current notice.</p>
 </>;
}
